persistentVolumeClaim:
  enabled: true
  storageClass: local-storage  # This uses the storage class defined local volume provisioner
  size: 500Mi

serviceWeb:
  loadBalancerIP: 192.168.1.122
  type: LoadBalancer
  http:
    enabled: true
  https:
    enabled: false

serviceDns:
  loadBalancerIP: 192.168.1.122
  type: LoadBalancer
